### ISSUE TITLE
Put an Image Chooser on the Website

### ISSUE THREAD

**Issue by Gottox** [freifunkks/freifunkks.github.com#2]
Hi!

The website still misses a download section for choosing and downloading the right image. There's #1  with a prototype, but I didn't want increase the bus factor of freifunkks any further. So please could you guys take over this work or throw away my work and start over?

kind regards

Enno

**Comment by flxai** [comment]
How about something like this?
![ffks_downloads_mockup](https://cloud.githubusercontent.com/assets/10831300/6198751/99aa3d32-b416-11e4-8a51-9003aae0ae54.gif)

**Comment by jplatte** [comment]
I think I can do something with that mockup. I'll attach a screenshot here once I have something done, as I know not everyone here can already build the site locally.

**Comment by jplatte** [comment]
Alright, here is the first screenshot. I'll commit this when I'm done adding all the devices from the js file @Gottox created. ([this one](https://github.com/freifunkks/freifunkks.github.com/blob/firmware_chooser/js/firmware.js))

![screenshot](https://cloud.githubusercontent.com/assets/951129/6200795/4f16552c-b488-11e4-8bd3-85e6696565d7.png)

**Comment by jplatte** [comment]
Commit done and pushed! I pushed to master so I can simply link to the new page here now. It shouldn't be a problem since the new page is not linked to anywhere. [Apart from here](http://www.ffks.de/firmware/).

There is no functionality yet, but that is because I would like to avoid JavaScript altogether here. @Gottox, would it be possible to have a script on the server select the right image from some form data (e.g. http://dl.ffks.de/images/dl.scriptExt?channel=stable&vendor=dlink&device=dir-825&version=rev-b1 would redirect to http://dl.ffks.de/images/stable/factory/gluon-ffks-2015.02.07.11-d-link-dir-825-rev-b1.bin)

**Comment by Gottox** [comment]
I'd like to avoid server side code on the gateway. (that's where the images are hosted too)

**Comment by jplatte** [comment]
Well, I don't really care which server this script would be on, but I can understand that you don't want it to be on the gateway. Would there be another option or do you think we have to do the download url concatenation with JS?

**Comment by jplatte** [comment]
We have a server-side script that is starting to work now: https://github.com/freifunkks/freifunkks.github.com/commit/79377540c555bf178d2e297b5b60839d26642dc5. The whole firmware page doesn't yet support selecting a hardware version which is needed for some routers, and the build date is still hardcoded, but if these problems are fixed, we can finally "release" (link to) the firmware download page.
